#!/bin/bash

# File:         testscript
# Author:       Stephen Bennett
# Project:      CSCI 3753 Programming Assignment 3
# Create Date:  2013/03/21
# Modify Date:  2013/03/21
# Description:
#   A bash script to run each test case and gather the relevant data.

LOW=10
MEDIUM=50
HIGH=500
#ITERATIONS=100000000
ITERATIONS=100000
BYTESTOCOPY=102400
BLOCKSIZE=1024
TIMEFORMAT="wall=%e user=%U system=%S CPU=%P preempted=%c blocked=%w"
MAKE="make -s"

echo Building code...
$MAKE clean
$MAKE

echo Making $HIGH copies of rwinput so each process has its own identical input file...
for i in $(seq 1 $HIGH); do cp rwinput rwinput-$i; done
echo

printf "Starting test runs...\n"

for SCHED in SCHED_OTHER SCHED_FIFO SCHED_RR; do
    for CHILDREN in $LOW $MEDIUM $HIGH; do
        echo Calculating pi over $ITERATIONS iterations
        echo using $SCHED scheduler with $CHILDREN simultaneous processes...
        INFO=`/usr/bin/time -f "$TIMEFORMAT" ./pi-sched $ITERATIONS $SCHED $CHILDREN > /dev/null`
        echo $INFO
    done

    for CHILDREN in $LOW $MEDIUM $HIGH; do
        echo Copying $BYTESTOCOPY bytes in blocks of $BLOCKSIZE from rwinput to rwoutput
        echo using $SCHED scheduler with $CHILDREN simultaneous processes...
        INFO=`/usr/bin/time -f "$TIMEFORMAT" ./rw-sched $BYTESTOCOPY $BLOCKSIZE default default SCHED_OTHER $CHILDREN > /dev/null`
        echo $INFO
    done
done
