#!/bin/bash

# File:         testscript
# Author:       Stephen Bennett
# Project:      CSCI 3753 Programming Assignment 3
# Create Date:  2013/03/21
# Modify Date:  2013/03/21
# Description:
#   A bash script to run each test case and gather the relevant data.

techo()
{
    echo "$1" | tee -a "$RESFILE"
}

LOW=10
MEDIUM=50
HIGH=500
RESFILE="results2.txt"
ITERATIONS=100000000
BYTESTOCOPY=102400
BLOCKSIZE=1024
INTERMEDIATERESULTS=50
ITERATIONSPERWRITE=1000000
TIMEFORMAT="wall=%e, user=%U, system=%S, CPU=%P, preempted=%c, blocked=%w"
MAKE="make -s"

printf "Building code...\n"
$MAKE clean
$MAKE

printf "Making $HIGH copies of rwinput so each process has its own identical input file...\n"
for i in $(seq 1 $HIGH); do cp rwinput rwinput-$i; done
echo

printf "Starting test runs...\n\n"

#for SCHED in SCHED_OTHER SCHED_FIFO SCHED_RR; do
    #techo "=============================================================================="
    #techo "TEST :: CPU BOUND"
    #techo "SCHEDULER       = $SCHED"
    #techo "ITERATIONS      = $ITERATIONS"
    #techo ""
    #for CHILDREN in $LOW $MEDIUM $HIGH; do
        #techo "CHILD PROCESSES = $CHILDREN"
        #/usr/bin/time -o "$RESFILE" -a -f "$TIMEFORMAT" ./pi-sched $ITERATIONS $SCHED $CHILDREN > /dev/null
        ##{ /usr/bin/time -f "$TIMEFORMAT" ./pi-sched $ITERATIONS $SCHED $CHILDREN > /dev/null ; } 2>> temp.txt
        #techo ""
    #done
#done

#for SCHED in SCHED_OTHER SCHED_FIFO SCHED_RR; do
    #techo "=============================================================================="
    #techo "TEST :: I/O BOUND"
    #techo "SCHEDULER       = $SCHED"
    #techo "BYTES TO COPY   = $BYTESTOCOPY"
    #techo "BLOCK SIZE      = $BLOCKSIZE"
    #techo ""
    #for CHILDREN in $LOW $MEDIUM $HIGH; do
        #techo "CHILD PROCESSES = $CHILDREN"
        #/usr/bin/time -o "$RESFILE" -a -f "$TIMEFORMAT" ./rw-sched $BYTESTOCOPY $BLOCKSIZE default default $SCHED $CHILDREN > /dev/null
        #techo ""
    #done
#done

for SCHED in SCHED_OTHER SCHED_FIFO SCHED_RR; do
    techo "=============================================================================="
    techo "TEST :: MIXED"
    techo "SCHEDULER       = $SCHED"
    techo "INTERMED WRITES = $INTERMEDIATERESULTS"
    techo "ITERATIONS/WRITE= $ITERATIONSPERWRITE"
    techo ""
    for CHILDREN in $LOW $MEDIUM $HIGH; do
        techo "CHILD PROCESSES = $CHILDREN"
        /usr/bin/time -o "$RESFILE" -a -f "$TIMEFORMAT" ./mix-sched $INTERMEDIATERESULTS $ITERATIONSPERWRITE default $SCHED $CHILDREN > /dev/null
        techo ""
    done
done
